=== George-MN/tibco-codereview/code-review-resources/src/main/resources/bw/BWRules/CodeReview/Resources/XSD/Lang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (C) Copyright 2011-2015 FastConnect SAS
    (http://www.fastconnect.fr/) and others.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns:lang="http://fastconnect.fr/Lang.xsd"
	 targetNamespace="http://fastconnect.fr/Lang.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="lang">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lang:word" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="lang" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="word">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="key" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== George-MN/tibco-codereview/code-review-resources/src/main/resources/bw/BWRules/CodeReview/Resources/Lang/FR.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--

    (C) Copyright 2011-2015 FastConnect SAS
    (http://www.fastconnect.fr/) and others.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<lang lang = "FR" xmlns = "http://fastconnect.fr/Lang.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://fastconnect.fr/Lang.xsd ../XSD/Lang.xsd">
	<word key = "Above max process call depth for analysis">A delà du seuil de profondeur d'appels durant l'analyse</word>
	<word key = "Activities count">Nombre d'activités</word>
	<word key = "Activity">Activité</word>
	<word key = "Binaries">Binaires</word>
	<word key = "Color">Couleur</word>
	<word key = "Condition">Condition</word>
	<word key = "Configuration">Configuration</word>
	<word key = "ConfigurationEntry">Paramètre</word>
	<word key = "Context">Contexte</word>
	<word key = "Disabled">Désactivé</word>
	<word key = "EFF">Efficacité</word>
	<word key = "EFF-001">Boucles imbriquées, niveau d'imbrication >= </word>
	<word key = "EFF-002">Section critique autour d'une Job Shared Variable</word>
	<word key = "EFF-003">Section critique autour d'un accès isolé à une Shared Variable</word>
	<word key = "EFF-004">Utilisation de l'activité Get JMS Queue Message</word>
	<word key = "EFF-005">Selectors JMS</word>
	<word key = "EFF-006">Utilisation des activités JMS synchrones</word>
	<word key = "ERR">Erreurs</word>
	<word key = "Error">Erreur</word>
	<word key = "File">Fichier</word>
	<word key = "Files">Fichiers</word>
	<word key = "From">De</word>
	<word key = "GEN">Général</word>
	<word key = "GEN-001">Informations générales</word>
	<word key = "GEN-002">Connexions non configurables</word>
	<word key = "GEN-003">Target namespace non-défini</word>
	<word key = "GEN-004">Collision de namespace</word>
	<word key = "Group">Groupe</word>
	<word key = "Informations">Informations</word>
	<word key = "Leaf Processes">Sous-processus</word>
	<word key = "Leaf process">Sous-processus</word>
	<word key = "MAI">Maintenabilité</word>
	<word key = "MAI-001">Couleurs utilisées pour les transitions</word>
	<word key = "MAI-002">Appels dynamiques de sous-process</word>
	<word key = "MAI-003">Appels consécutifs de sous-process >= </word>
	<word key = "MAI-004">Extensions Java XPath</word>
	<word key = "MAI-005">Imports de librairies invalides</word>
	<word key = "MAI-006">Mapper d'entrée complexe, > </word>
	<word key = "MAI-007">Nombre d'activités par processus > </word>
	<word key = "MAI-008">Processus non-commentés</word>
	<word key = "MAI-009">Processus trop grands, > </word>
	<word key = "MAI-010">Transitions sans label</word>
	<word key = "MAI-011">Starter avec schéma de sortie</word>
	<word key = "Max depth">Profondeur max</word>
	<word key = "Namespace">Namespace</word>
	<word key = "Not well formed connection">Connexion</word>
	<word key = "Number of activities">Nombre d'activités : </word>
	<word key = "Number of adapter archives">Nombre d'adapter archives (aar) : </word>
	<word key = "Number of enterprise archives">Nombre d'entreprise archives (ear) : </word>
	<word key = "Number of files">Nombre de fichiers : </word>
	<word key = "Number of process archives">Nombre de process archives (par) : </word>
	<word key = "Number of processes">Nombre de processus : </word>
	<word key = "Number of project libraries builder">Nombre de library builder : </word>
	<word key = "Number of project libraries used">Nombre de librairies utilisées : </word>
	<word key = "POR">Portabilité</word>
	<word key = "POR-001">Utilisation de l'activité External Command</word>
	<word key = "POR-002">Utilisation des activités Java</word>
	<word key = "Process">Processus</word>
	<word key = "Processes">Processus</word>
	<word key = "Property">Propriété</word>
	<word key = "REL">Fiabilité</word>
	<word key = "REL-001">Appels récursifs</word>
	<word key = "REL-002">Transactions imbriquées</word>
	<word key = "REL-003">Utilisations de l'activité JDBC SQL Direct</word>
	<word key = "REL-004">Prioriétés JMS inconnues</word>
	<word key = "REL-005">Activités sans transition de sortie</word>
	<word key = "REL-006">Transition otherwise manquante</word>
	<word key = "Reason">Détection</word>
	<word key = "Recursion checked">Récursion vérifiée</word>
	<word key = "Resource">Ressource</word>
	<word key = "Resources">Ressource</word>
	<word key = "Rule">Règle</word>
	<word key = "Stack">Stack</word>
	<word key = "Sources">Sources</word>
	<word key = "To">Vers</word>
	<word key = "Transition type">Type de transition</word>
	<word key = "Value">Valeur</word>
	<word key = "XPath">XPath</word>
	<word key = "subtitle">pour TIBCO BusinessWorks</word>
	<word key = "title">FC Code Review</word>
</lang>

=== George-MN/tibco-codereview/code-review-resources/src/main/resources/bw/BWRules/CodeReview/Resources/Lang/EN.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<lang lang = "FR" xmlns = "http://fastconnect.fr/Lang.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://fastconnect.fr/Lang.xsd ../XSD/Lang.xsd">
	<word key = "Above max process call depth for analysis">Above max process call depth while analysing</word>
	<word key = "Activities count">Activities count</word>
	<word key = "Activity">Activity</word>
	<word key = "Binaries">Binaires</word>
	<word key = "Color">Color</word>
	<word key = "Condition">Condition</word>
	<word key = "Configuration">Configuration</word>
	<word key = "ConfigurationEntry">Parameter</word>
	<word key = "Context">Context</word>
	<word key = "Disabled">Disabled</word>
	<word key = "EFF">Efficiency</word>
	<word key = "EFF-001">Nested loops, nesting >= </word>
	<word key = "EFF-002">Critical Section around a Job Shared Variable</word>
	<word key = "EFF-003">Critical Section around a single Shared Variable access</word>
	<word key = "EFF-004">Uses of Get JMS Queue Message</word>
	<word key = "EFF-005">JMS selectors</word>
	<word key = "EFF-005">Uses of synchronous JMS activities</word>
	<word key = "ERR">Errors</word>
	<word key = "Error">Error</word>
	<word key = "File">File</word>
	<word key = "Files">Files</word>
	<word key = "From">From</word>
	<word key = "GEN">General</word>
	<word key = "GEN-001">General informations</word>
	<word key = "GEN-002">Connections not configurable</word>
	<word key = "GEN-003">Target namespace not defined</word>
	<word key = "GEN-004">Namespace collision</word>
	<word key = "Group">Group</word>
	<word key = "Informations">Informations</word>
	<word key = "Leaf Processes">Sub-process</word>
	<word key = "Leaf process">Sub-process</word>
	<word key = "MAI">Maintainability</word>
	<word key = "MAI-001">Colors used for transitions</word>
	<word key = "MAI-002">Dynamic Call Process overrides</word>
	<word key = "MAI-003">Successive sub-process calls >= </word>
	<word key = "MAI-004">Java XPath extensions</word>
	<word key = "MAI-005">Invalid projlib imports</word>
	<word key = "MAI-006">Complex activity input, > </word>
	<word key = "MAI-007">Number of activities by process > </word>
	<word key = "MAI-008">Processus non-comment√©s</word>
	<word key = "MAI-009">Oversized processes, > </word>
	<word key = "MAI-010">Unlabelled transition</word>
	<word key = "MAI-011">Starter processes with output</word>
	<word key = "Max depth">Max depth</word>
	<word key = "Namespace">Namespace</word>
	<word key = "Not well formed connection">Connection</word>
	<word key = "Number of activities">Number of activities: </word>
	<word key = "Number of adapter archives">Number of adapter archives (aar): </word>
	<word key = "Number of enterprise archives">Number of enterprise archives (ear): </word>
	<word key = "Number of files">Number of files: </word>
	<word key = "Number of process archives">Number of process archives (par): </word>
	<word key = "Number of processes">Number of processes: </word>
	<word key = "Number of project libraries builder">Number of library builder: </word>
	<word key = "Number of project libraries used">Number of project libraries used: </word>
	<word key = "POR">Portability</word>
	<word key = "POR-001">Uses of External Command</word>
	<word key = "POR-002">Uses of Java activities</word>
	<word key = "Process">Process</word>
	<word key = "Processes">Processes</word>
	<word key = "Property">Property</word>
	<word key = "REL">Reliability</word>
	<word key = "REL-001">Recursive calls</word>
	<word key = "REL-002">Nested transactions</word>
	<word key = "REL-003">Uses of JDBC SQL Direct</word>
	<word key = "REL-004">Unknown JMS properties</word>
	<word key = "REL-005">Activities with no out transition</word>
	<word key = "REL-006">Missing otherwise transition</word>
	<word key = "Reason">Detection</word>
	<word key = "Recursion checked">Checked recursion</word>
	<word key = "Resource">Resource</word>
	<word key = "Resources">Resources</word>
	<word key = "Rule">Rule</word>
	<word key = "Sources">Sources</word>
	<word key = "Stack">Stack</word>
	<word key = "To">To</word>
	<word key = "Transition type">Transition type</word>
	<word key = "Value">Value</word>
	<word key = "XPath">XPath</word>
	<word key = "subtitle">for TIBCO BusinessWorks</word>
	<word key = "title">FC Code Review</word>
</lang>
